#!/usr/bin/env bash

dest="results/page_fault/page_fault_costs"
res="results.out"
ram="/dev/ram0"
pmem="/dev/pmem0"
mnt="/mnt/mem"
workload="workloads/page_fault/page_fault_reg.txt"
workload_anon="workloads/page_fault/page_fault_anon.txt"

cd ..
mkdir -p results/page_fault
touch $dest

mount_fs() {
    if [[ $1 == *"pmem"* ]]; then
        sudo mount $1 -o dax $2 &> /dev/null
    else
        sudo mount $1 $2 &> /dev/null
    fi
}

umount_fs() {
    sudo umount $1
}

run_cmd() {
    for i in {1..5}
    do
        sudo ./Benchmark -file=$1 &>/dev/null
        awk '{if(/Average latency\t*/) print $3}' < results.out >> $dest
    done
    echo "" >> $dest
}

sudo mkdir -p $mnt
echo "Clearing $dest"
> $dest

echo "Creating and Mounting ext4 on $ram"
sudo mkfs.ext4 -F $ram &> /dev/null 
mount_fs $ram $mnt
echo "Running ext4 bench"
echo "ext4: " >> $dest
run_cmd $workload
echo "Finished ext4 bench"
echo "Unmounting ext4"
sudo umount $ram &> /dev/null

echo "Creating and Mounting xfs on $ram"
sudo mkfs.xfs $ram -f &> /dev/null
mount_fs $ram $mnt
echo "Running xfs bench"
echo "xfs: " >> $dest
run_cmd $workload
echo "Finished xfs bench"
echo "Unmounting xfs"
umount_fs $ram

echo "Creating and Mounting ext4-dax on $pmem"
sudo mkfs.ext4 $pmem -f &> /dev/null
mount_fs $pmem $mnt
echo "Running ext4-dax bench"
echo "ext4-dax: " >> $dest
run_cmd $workload
echo "Finished ext4-dax bench"
echo "Unmounting ext4-dax"
sudo umount $pmem &> /dev/null

echo "Creating and Mounting xfs-dax on $pmem"
sudo mkfs.xfs -m reflink=0 $pmem -f &> /dev/null
mount_fs $pmem $mnt
echo "Running xfs-dax bench"
echo "xfs-dax: " >> $dest
run_cmd $workload
echo "Finished xfs-dax bench"
echo "Unmounting xfs-dax"
sudo umount $pmem &> /dev/null

echo "Running MAP_ANONYMOUS"
echo "map_anon: " >> $dest
run_cmd $workload_anon
echo "Finished MAP_ANONYMOUS bench"

echo "Results:"
cat $dest
